# Site settings
title: Fietsknelpunten.be
email:
description: > # this means to ignore newlines until "baseurl:"
  Meldpunt voor fietsknelpunten
baseurl: /blog # the subpath of your site, e.g. /blog/
url: "http://fietsknelpunten.be" # the base hostname & protocol for your site
twitter_username: lieven

# Build settings
markdown: kramdown
